name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: meanori/organization-management-frontend
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: login to docker hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Run docker build
      run: docker build --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} --no-cache -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .

    - name: Tag Docker image as dev
      run: |
        docker tag ${{ env.DOCKER_IMAGE }}:${{ github.sha }} ${{ env.DOCKER_IMAGE }}:dev

    - name: push to docker hub with tag github commit
      run: docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

    - name: push to docker hub with tag dev
      run: docker push ${{ env.DOCKER_IMAGE }}:dev