name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: meanori/organization-management-frontend
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Run docker build
      run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .

    - name: push to docker hub
      run: docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

        
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.EC2_BASTION_HOST_KEY_PAIR }}" > ~/.ssh/bastion_host_key_pair.pem
        chmod 400 ~/.ssh/bastion_host_key_pair.pem
        
        echo "${{ secrets.EC2_FRONTEND_KEY_PAIR }}" > ~/.ssh/frontend_key_pair.pem
        chmod 400 ~/.ssh/backend_key_pair.pem

    - name: Configure SSH
      run: |
        echo "
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
        Host bastion-host
            HostName ${{ secrets.EC2_BASTION_HOST_IP }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/bastion_host_key_pair.pem
        
        Host frontend
            HostName ${{ secrets.EC2_FRONTEND_IP }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/frontend_key_pair.pem
            ProxyJump bastion-host
        " > ~/.ssh/config
    - name: Copy .env file 
      run:
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null .env ${{ secrets.SSH_USER }}@frontend:.env

    - name: Copy docker-compose.yml
      run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker-compose.yml ${{ secrets.SSH_USER }}@frontend:docker-compose.yml


    - name: Deploy to EC2
      run: |
        ssh frontend '
          docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          sudo docker compose down
          sudo docker compose --env-file .env up -d
        '
    - name: Clean key pairs
      if: always()
      run: |
        rm -f ~/.ssh/bastion_host_key_pair.pem ~/.ssh/frontend_key_pair.pem
