name: CI frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: meanori/organization-management-frontend
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-push-dev:
    name: Build and push to dev

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Run Docker build
      run: |
        docker build --no-cache -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .

    - name: Add tag dev to docker image
      run: |
        docker tag ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} ${{ env.DOCKER_IMAGE }}:dev

    - name: Push to Docker Hub with commit hash tag
      run: |
        docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

    - name: Push to Docker Hub with dev tag
      run: |
        docker push ${{ env.DOCKER_IMAGE }}:dev
