name: Get Commit Hash from Git Tag

on:
  release:
    types:
      - published

env:
  DOCKER_IMAGE: meanori/organization-management-frontend

jobs:
  get_commit_hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Verify Git repository
        run: git status

      - name: Get commit hash for the release tag
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          # Extract the tag name from the GITHUB_REF variable
          tag_name=$(basename $GITHUB_REF)
          echo "Tag name: $tag_name"

          # Get the commit hash associated with the tag
          commit_hash=$(git rev-list -n 1 $tag_name)
          echo "Commit hash for tag $tag_name: $commit_hash"
          echo "COMMIT_HASH=${commit_hash}" > $GITHUB_ENV
          echo "TAG=${tag_name}" > $GITHUB_ENV

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: add tag prod for exist image and push to docker hub
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}:${{ env.COMMIT_HASH }}
          docker tag ${{ env.DOCKER_IMAGE }}:${{ env.COMMIT_HASH }} ${{ env.DOCKER_IMAGE }}:${{ ENV.TAG }}
          docker push ${{ env.DOCKER_IMAGE }}:${{ ENV.TAG }}
    


